### ISSUE TITLE
Missing archs for images on dockerhub (Probably pipeline issue). Since 0.5.3-alpha.7

### ISSUE THREAD

**Issue by pascaldornfeld** [revoltchat/backend#116]
When launching the self-hosted [docker-compose](https://github.com/revoltchat/self-hosted/blob/master/docker-compose.yml) I am getting errors with the api/server part. 

`api_1            | standard_init_linux.go:219: exec user process caused: exec format error`

I am getting the same with revoltchat/server:latest, 0.5.3-alpha.8 and 0.5.3-alpha.7 but revoltchat/server:master works fine. I didn't try older tags.

---

I found out that the error is usually connected to a wrong image arch. My system is amd64.

$ uname -a
Linux debian-server 5.10.0-9-amd64 #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64 GNU/Linux

After checking dockerhub I found out that master has only amd64 arch while the other have arm64.
See [this](https://hub.docker.com/r/revoltchat/server/tags):

![image](https://user-images.githubusercontent.com/52472959/140961318-7a03a71e-2da3-4676-9b97-7227b9b85a90.png)

**Comment by insertish** [comment]
It seems that the GitHub action I have when it gets to building arm64, it seems to delete amd64 images (??)
I have temporarily just removed arm64 builds until I have a chance to fix this.
`master` is currently equal to `0.5.3-apha.8`.

**Comment by insertish** [comment]
Closing in favour of https://github.com/revoltchat/backend/issues/142
