### ISSUE TITLE
Prevent unverified accounts from logging if verification link has not been clicked.

### ISSUE THREAD

**Issue by davidmroth** [revoltchat/backend#126]
When `` is enabled, user are still able to login even before the login and email is verified (via email)

Steps to reproduce:

1. Enable `REVOLT_USE_EMAIL_VERIFICATION=1 & REVOLT_UNSAFE_NO_EMAIL=0`
2. Register - user will be notified that an email has been sent
3. Goto login page and login before email is verified
4. User is able to login

An upstream (rauth) pull request created that resolves the issue: https://github.com/insertish/rauth/issues/32

After changes in pull request, users will need to verify email before being able to login. If not, user will receive a login error:

![image](https://user-images.githubusercontent.com/10832/146660603-11e1ba57-f4c8-4abe-9225-a078d42742d9.png)

**Comment by insertish** [comment]
This was fixed.
