### ISSUE TITLE
Basic "Oauth" Server

### ISSUE THREAD

**Issue by nerrixDE** [revoltchat/backend#127]
While not following the specs of Oauth, until a full integration is possible with all the consequences (authorize screen, scope definitons, security policies, and so on) (very complex, time-intense and easy to do wrong)

a basic oauth-like alternative for internal resouces should be added:
Design: https://discord.com/channels/627422790571524097/916811887813988402/921482106851442698 (Internal Resource).
This design (may be adjusted) could be added easily and would prevent Revolt upstream blocking progress with revolt.social

**Comment by insertish** [comment]
Superseded by https://github.com/authifier/authifier/issues/35.
