### ISSUE TITLE
With Enough Blocked Messages, Revolt Web (or perhaps the API) Refuses to Load Additional Messages

### ISSUE THREAD

**Issue by kcseb** [revoltchat/backend#147]
![image](https://user-images.githubusercontent.com/26828446/160946645-81b35fb3-af97-4dc1-a33f-611a829dc69d.png)
As shown, Due to the high volume of messages from a blocked user/blocked users, either Revolt (app) or Delta (revolt API) fails to resolve and display the messages before said blocked messages. 
This results in a large empty space where previous messages should have been displayed. 
Commit: cf049bd4ee1ccd6f630a09345d104184091294da

**Comment by insertish** [comment]
Closing due to rewrite, https://github.com/revoltchat/frontend.
https://github.com/revoltchat/frontend/issues/134
