### ISSUE TITLE
issue: Unnecessary preflight request in API

### ISSUE THREAD

**Issue by tinopai** [revoltchat/backend#164]
Due to the subdomain difference between the **app** (app.revolt.chat) and the **API** (api.revolt.chat) browsers require that OPTIONS request due to CORS.
![image](https://user-images.githubusercontent.com/66493488/168633327-34a0cbcc-b5be-4c3f-a3d1-f7f5d9e2f69e.png)

But it's useless in my opinion and takes extra time and bandwidth to send POST (PUT, PATCH, DELETE, etc...) requests to the API thus making the app-api handshake slower.
My possible solutions are:
- Move **app.revolt.chat** to **revolt.chat/app** and API to **revolt.chat/api**
- Cache the preflight request by adding the `Access-Control-Max-Age` header
- Make an alias to **app.revolt.chat/api**

I'm not sure if this is the repo to file the issue in, so correct me if I'm wrong.

**Comment by insertish** [comment]
Solved in new client infrastructure.
