### ISSUE TITLE
feature request: self-banning

### ISSUE THREAD

**Issue by erkinalp** [revoltchat/backend#181]
### What do you want to see?

A user should be able to ban itself from a guild or entire instance even. For safety reasons, guild and instance moderators should not be able to view and/or revoke self-bans.

**Comment by Rexogamer** [comment]
Hmmm - just out of curiosity, what kind of scenarios would this be used in?

**Comment by erkinalp** [comment]
Counter-defence against abusive moderators and/or communities.

**Comment by Rexogamer** [comment]
I was more so wondering why you'd need to self ban yourself from a server/instance instead of, say, leaving and not rejoining/deleting your account respectively

**Comment by I2rys** [comment]
Hmmm. You can just leave the server though 🤔

**Comment by Evilhotdog** [comment]
@erkinalp am I right in reading that the idea of this is that a user can safely 'slip out the back' without creating any sort of announcement?

**Comment by erkinalp** [comment]
@Evilhotdog Yes, exactly.

**Comment by Rexogamer** [comment]
This sounds more like a silent leave feature to me - it might be worth renaming the issue

**Comment by erkinalp** [comment]
No, it is actually intended to affect the ban list.

**Comment by Rexogamer** [comment]
I see - I'm again just wondering what exactly this would be useful for, especially as opposed to some sort of silent leave feature...?

**Comment by erkinalp** [comment]
@Rexogamer In enterprise contexts, you sometimes force join users. Self-banning would protect against abusive force joiners.

**Comment by Rexogamer** [comment]
The instance owner could just... remove the ban?

**Comment by Rexogamer** [comment]
We've discussed this internally and we're still not entirely sure how this would be used or, more importantly, how to implement this in a way that isn't reversible by the instance owner. I'm going to close this issue, but feel free to elaborate further on this idea/how it would be used and implemented. Thanks!
