### ISSUE TITLE
fix: ignore anchor (#abc) in link

### ISSUE THREAD

**Issue by TibbeD** [revoltchat/backend#183]
### What happened?

When sending multiple exactly the same urls, there is only one embed, as twice the same embed would be unneccesary, but when sending multiple urls that link to the same page but to a different anchor, there are multiple embeds, even though this also results in multiple times the same embed.

### Branch

Production (app.revolt.chat)

### Commit hash

[`eb1bd27`](https://github.com/revoltchat/revite/commit/eb1bd27ec0e491c8a747c4bb442eb7dfb0aa6350)

### What browsers are you seeing the problem on?

Firefox

### Desktop

- [ ] Yes, this bug is specific to Revolt Desktop and is *not* an issue with Revolt Desktop itself.

### PWA

- [ ] Yes, this bug is specific to the PWA.

**Comment by insertish** [comment]
Before:
![image](https://user-images.githubusercontent.com/38285861/174768977-46c3cf21-e083-4b37-9d1e-f881923f44e5.png)

After:
![image](https://user-images.githubusercontent.com/38285861/174768995-b4e34dd0-7038-400f-971e-3debbcb02de2.png)
