### ISSUE TITLE
bug: 403 Error on Role Deletion

### ISSUE THREAD

**Issue by SlushUwU** [revoltchat/backend#200]
### What happened?

I deleted all Channels on my Server because I want to rebuild it and as soon as I wanted to delete the Roles I get in the Console the following error:
![image](https://user-images.githubusercontent.com/105487011/189503797-563511d8-92a9-4ab5-80e8-e1900112c6fd.png)

**Comment by ryanalexander** [comment]
I am struggling to replicate this. Can you provide some more detail on the steps you took for this? and can you still replicate it?

**Comment by SlushUwU** [comment]
Heres a Video:
https://user-images.githubusercontent.com/105487011/194683872-8cca1535-635b-48cb-9193-08879a86c4ad.mp4
