### ISSUE TITLE
bug: 404 error when adding new user as friend

### ISSUE THREAD

**Issue by MingTheNoob** [revoltchat/backend#211]
### What happened?

Attempting to add a friend results in a 404 error. 

Error message: `ERROR: REQUEST FAILED WITH STATUS CODE 404`

**Comment by MingTheNoob** [comment]
Update: Only happens when adding friend from home screen. Adding friend in mutual server is possible and does not result in a error

**Comment by toastxc** [comment]
In testing a self hosted instance i was not able to replicate this error.
Can you provide any further details for replicating this error?

**Comment by insertish** [comment]
Closing due to no follow up
