### ISSUE TITLE
feature request: Issue tags specifying crate

### ISSUE THREAD

**Issue by toastxc** [revoltchat/backend#212]
### What do you want to see?

It might be useful to assign a label based on what create the issue affects (if applicable) since there are multiple projects in the same repository

**Comment by Zomatree** [comment]
Ive added some more tags, let me know if you need anymore.
![chrome_UrL11HxBE0](https://user-images.githubusercontent.com/39768508/210292854-5ae41409-a0e9-4e1d-bdbe-018fa4e7cec1.png)
