### ISSUE TITLE
bug: ServerCreate event missing emoji data for new server, only on Ready event for old servers

### ISSUE THREAD

**Issue by xXBuilderBXx** [revoltchat/backend#243]
### What happened?

The websocket event for ServerCreate is missing a list of emojis which causes some inconsistency when using/caching/checking emojis which means that servers your bot joins has no existing emojis and there is no API to fetch a list of emojis for a server either.
![image](https://user-images.githubusercontent.com/17956143/236652920-2bfe0c2b-a1b5-4483-9302-2491723ff0c2.png)

A fix for this would be adding emoji data to the ServerCreate event.

**Comment by Rexogamer** [comment]
This also causes issues in the frontend - when you initially join a server, you can't access its emojis in the emoji picker without reloading
