### ISSUE TITLE
Configurable max server / channel limit for users.

### ISSUE THREAD

**Issue by insertish** [revoltchat/backend#25]

**Comment by insertish** [comment]
Blocking on #18

**Comment by erkinalp** [comment]
@insertish Why would one need an artificial limit? Discord and Guilded impose those limits due to client performance issues, not due to server performance issues.

**Comment by insertish** [comment]
It doesn't need to be as low as Discord or Guilded, but mainly for mitigating abuse.
I doubt most users need more than 250 servers or so on a single instance.

**Comment by Rushmore75** [comment]
Could probably just do a `-1` or something for no artificial limit? Just have it translate under the hood to `usize::max` or whatever unit is used to hold that quantity

**Comment by insertish** [comment]
This was implemented at some point (Revolt.toml => features)

**Comment by insertish** [comment]
> Could probably just do a `-1` or something for no artificial limit? Just have it translate under the hood to `usize::max` or whatever unit is used to hold that quantity

If you're interested in this feature, please open another issue.
