### ISSUE TITLE
bug: failed to compile syn

### ISSUE THREAD

**Issue by PotatoSUS** [revoltchat/backend#264]
### What happened?

hi, im trying to setup revolt backend and when i run the project i get the error: ```ubuntu@mail:~/backend$ cargo run --bin revolt-bonfire
   Compiling syn v1.0.107
thread 'rustc' panicked at 'assertion failed: pos.get() <= self.position()', compiler/rustc_metadata/src/rmeta/encoder.rs:433:9
error: could not compile `syn` (lib)```
![image](https://github.com/revoltchat/backend/assets/82276088/1dc663db-9ad5-4f5b-9ca3-186687976cd0)

**Comment by insertish** [comment]
MSRV is Rust 1.70, that's probably your issue.

Can't help beyond that because CI and dev builds are working fine.
