### ISSUE TITLE
refactor: drop quark dependency from web routes

### ISSUE THREAD

**Issue by insertish** [revoltchat/backend#283]
Routes still using quark crate:

- [x] channel/ack
- [x] channel/delete
- [x] channel/edit
- [x] group/add_member
- [x] group/remove_member
- [x] invite/create
- [x] members/fetch
- [x] messages/bulk_delete
- [x] messages/clear_reactions
- [x] messages/delete
- [x] messages/edit
- [x] messages/query
- [x] messages/react
- [x] messages/search
- [x] messages/unreact
- [x] channel/permissions/set_default
- [x] channel/permissions/set_role
- [x] channel/voice/join
- [x] channel/webhook/create
- [x] channel/webhook/fetch_all
- [x] emoji/create
- [x] emoji/delete
- [x] emoji/fetch
- [x] invite/delete
- [x] invite/fetch
- [x] invite/join
- [x] onboard/complete
- [x] onboard/hello
- [x] push/sub
- [x] push/unsub
- [x] safety/report_content
- [x] server/ban_create
- [x] server/ban_list
- [x] server/ban_remove
- [x] server/channel_create
- [x] server/emoji_list
- [x] server/invites_list
- [x] server/member_edit
- [x] server/all_members
- [x] server/fetch_member
- [x] server/kick_member
- [x] server/permissions/set_default
- [x] server/permissions/set_role
- [x] server/roles/create
- [x] server/roles/delete
- [x] server/roles/edit
- [x] server/ack
- [x] server/create
- [x] server/delete
- [x] server/edit
- [x] server/fetch
- [x] sync/get_settings
- [x] sync/get_unreads
- [x] sync/set_settings
- [x] users/add_friend
- [x] users/block_user
- [x] users/change_username
- [x] users/edit_user
- [x] users/fetch_dms
- [x] users/fetch_profile
- [x] users/fetch_self
- [x] users/fetch_user_flags
- [x] users/fetch_user
- [x] users/find_mutual
- [x] users/open_dm
- [x] users/remove_friend
- [x] users/send_friend_request
- [x] users/unblock_user

**Comment by septante** [comment]
Hi,
I'd like to take on this issue (or at least part of it). Could someone sanity check my work for channel/ack? It should be linked above this comment.
