### ISSUE TITLE
bug: server emoji count can be 1 more than the set limit

### ISSUE THREAD

**Issue by amycatgirl** [revoltchat/backend#295]
### What happened?

As pointed out by [Toatrika#5321 on Revolt's Server](https://app.revolt.chat/server/01F7ZSBSFHQ8TA81725KQCSDDP/channel/01F92C5ZXBQWQ8KY7J8KY917NM/01HGS65T457V7N6XWM9HYG8R59), It seems like servers can have exactly one more emoji than the limit imposed by the server.

I checked the source code and found out that in [line 48 of customization/emoji_create.rs](https://github.com/revoltchat/backend/blob/25016efbc2bbe96fbe79f2dc1b29dee3c924007c/crates/delta/src/routes/customisation/emoji_create.rs#L48), the backend is checking if the server's emoji count is *greater than* the maximum limit, which means that a server can have 101 emotes.

## Proposed change (literally 2 characters that I am too lazy to change)

```diff
// ...

- if emojis.len() > config.features.limits.default.server_emoji {
+ if emojis.len() >= config.features.limits.default.server_emoji {
                return Err(create_error!(TooManyEmoji {
                    max: config.features.limits.default.server_emoji,
                }));
            }

// ...
```

**Comment by DevSmoger** [comment]
I found also this same bug. When Emojis reach to 100 and you delete saved emojis from the list, it doesn't delete older ones and after that I'm able to save more emojis to list, now there is 102 of them. Didn't check how many more this way I could add them.
Something is registering the delete button click, but the value doesn't decrees after that, it's like freeing up one slot and can add more then limit allows.
![Revolt_j5XRdZibqj](https://github.com/user-attachments/assets/1b8f7f92-cb25-459d-b13a-2283c60648d7)
