### ISSUE TITLE
Internal Error When Attempting To Create Account

### ISSUE THREAD

**Issue by ItsJustTee** [revoltchat/backend#300]
### What happened?

When attempting to create an account on https://app.revolt.chat/login/create Revolt throws an Error as "INTERNALERROR" 

Screenshot taken from Incognito Tab
![image](https://github.com/revoltchat/backend/assets/37266538/051df1f7-82ec-4f1f-895d-66c83653a485)

**Comment by Rexogamer** [comment]
We had a few outages earlier this year but I can create an account fine today - is this still an issue for you?

**Comment by ItsJustTee** [comment]
Closing as resolved.

**Comment by MasonGeloso** [comment]
Also tried with multiple emails and still no luck ;(

**Comment by coldReactive** [comment]
Having this issue now too.
