### ISSUE TITLE
bug: Glitching and not connecting

### ISSUE THREAD

**Issue by Mezame-ux** [revoltchat/backend#320]
### What happened?

It seems like revolt is refusing to connect.

[Screen recording 2024-06-11 18.17.19.webm](https://github.com/revoltchat/backend/assets/86276545/b18f9563-eaed-47ba-ab96-113b00c8dfd3)

**Comment by insertish** [comment]
Someone started attacking our network and certain clients got stuck reconnecting, operating as normal now.
