### ISSUE TITLE
bug: Cloudflare reporting Bad Gateway and SSL handshake error.

### ISSUE THREAD

**Issue by JF6DEU** [revoltchat/backend#328]
### What happened?

# Introduction
When I using Revolt, I found these errors.
![image](https://github.com/user-attachments/assets/1364de18-0870-49a1-afc3-029e314a8078)
![u](https://github.com/user-attachments/assets/c387921c-b8f3-4ac3-b953-f13fa332ab96)
I know these errors might be temporary error, but I thought it is an issue.

**Comment by JF6DEU** [comment]
And I got an error now:code is 520.
![スクリーンショット 2024-07-12 090734](https://github.com/user-attachments/assets/cb328c35-15ad-46b6-91ff-e9dd5b7a8371)

**Comment by JF6DEU** [comment]
It was temporarily fixed, but it recurred.
![IMG_0438](https://github.com/user-attachments/assets/791d08ed-5667-44fb-b6ba-a5166cfbc57a)
Error code is `525`, `SSL handshake failed`.

**Comment by insertish** [comment]
Cloudflare decided to stop talking to our server, more information here: https://memo.insert.moe/m/HDJg6MAVprPCmAbXFqYhPs
