### ISSUE TITLE
feature request: Account Login using Unique User Identifier + 2FA

### ISSUE THREAD

**Issue by Zig-Rust-Odin** [revoltchat/backend#383]
### What do you want to see?

Login , no email, no password,

revolt 
* Create a new account ---> Generate Unique User Identifier ---> Bind 2FA ---> Complete

![](https://user-images.githubusercontent.com/121728974/221565637-5705d0f7-7cf1-4168-856a-8598301be6f1.png)

- revolt Create a new account. EMail is no longer supported.
> But you can still log in with your email

---

> Encrypting Email
Don’t.
[Email is insecure](https://news.ycombinator.com/item?id=16088386). Even with PGP, it’s default-plaintext, which means that even if you do everything right, some totally reasonable person you mail, doing totally reasonable things, will invariably CC the quoted plaintext of your encrypted message to someone else (we don’t know a PGP email user who hasn’t seen this happen). PGP email is forward-insecure. Email metadata, including the subject (which is literally message content), are always plaintext. https://www.latacora.com/blog/2019/07/16/the-pgp-problem/

**Comment by Zomatree** [comment]
We don't plan on removing the email requirement, this is to help prevent spam and malicious use, moderation and contacting the user.
