### ISSUE TITLE
bug: INTERNALERROR - when registering

### ISSUE THREAD

**Issue by Ferdinand99** [revoltchat/backend#388]
### What happened?

Hi,

I want to register to revolt chat as I find it promising, but I have  a problem with the registration where I get a INTERNALERROR. I have tried bot the webapp, windows app and android app without any luck.

![Image](https://github.com/user-attachments/assets/324ad41a-0da7-43f8-91e5-a52f265721bc)

**Comment by insertish** [comment]
One of our internal services is having issues connecting to the database, I've just put in a more permanent fix and hopefully this will stop happening.
